# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import due_streaming_pb2 as due__streaming__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in due_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DueStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCommands = channel.stream_stream(
                '/due.DueStreaming/StreamCommands',
                request_serializer=due__streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=due__streaming__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.stream_stream(
                '/due.DueStreaming/StreamTelemetry',
                request_serializer=due__streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=due__streaming__pb2.TelemetryUpdate.FromString,
                _registered_method=True)


class DueStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamCommands(self, request_iterator, context):
        """Bidirectional streaming for commands and responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request_iterator, context):
        """Server-side streaming for telemetry data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DueStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCommands': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=due__streaming__pb2.StreamRequest.FromString,
                    response_serializer=due__streaming__pb2.StreamResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=due__streaming__pb2.StreamRequest.FromString,
                    response_serializer=due__streaming__pb2.TelemetryUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'due.DueStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('due.DueStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DueStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamCommands(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/due.DueStreaming/StreamCommands',
            due__streaming__pb2.StreamRequest.SerializeToString,
            due__streaming__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/due.DueStreaming/StreamTelemetry',
            due__streaming__pb2.StreamRequest.SerializeToString,
            due__streaming__pb2.TelemetryUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
