# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: due_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'due_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ue_streaming.proto\x12\x03\x64ue\"*\n\x0bVariantList\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.due.Variant\"|\n\rVariantStruct\x12.\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1e.due.VariantStruct.FieldsEntry\x1a;\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.due.Variant:\x02\x38\x01\"\xfd\x01\n\x07Variant\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x05 \x01(\x0cH\x00\x12&\n\nlist_value\x18\x06 \x01(\x0b\x32\x10.due.VariantListH\x00\x12*\n\x0cstruct_value\x18\x07 \x01(\x0b\x32\x12.due.VariantStructH\x00\x12$\n\nnull_value\x18\x08 \x01(\x0e\x32\x0e.due.NullValueH\x00\x42\x06\n\x04kind\"\xbc\x01\n\rStreamRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x1a\n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x0c.due.Variant\x12.\n\x06kwargs\x18\x03 \x03(\x0b\x32\x1e.due.StreamRequest.KwargsEntry\x12\x12\n\nrequest_id\x18\x04 \x01(\x04\x1a;\n\x0bKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.due.Variant:\x02\x38\x01\"Q\n\x0eStreamResponse\x12\x1c\n\x06result\x18\x01 \x01(\x0b\x32\x0c.due.Variant\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\xa5\x01\n\x0fTelemetryUpdate\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12<\n\x0cmeasurements\x18\x02 \x03(\x0b\x32&.due.TelemetryUpdate.MeasurementsEntry\x1a\x41\n\x11MeasurementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.due.Variant:\x02\x38\x01*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x32\x8e\x01\n\x0c\x44ueStreaming\x12=\n\x0eStreamCommands\x12\x12.due.StreamRequest\x1a\x13.due.StreamResponse(\x01\x30\x01\x12?\n\x0fStreamTelemetry\x12\x12.due.StreamRequest\x1a\x14.due.TelemetryUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'due_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARIANTSTRUCT_FIELDSENTRY']._loaded_options = None
  _globals['_VARIANTSTRUCT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_STREAMREQUEST_KWARGSENTRY']._loaded_options = None
  _globals['_STREAMREQUEST_KWARGSENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYUPDATE_MEASUREMENTSENTRY']._loaded_options = None
  _globals['_TELEMETRYUPDATE_MEASUREMENTSENTRY']._serialized_options = b'8\001'
  _globals['_NULLVALUE']._serialized_start=896
  _globals['_NULLVALUE']._serialized_end=923
  _globals['_VARIANTLIST']._serialized_start=28
  _globals['_VARIANTLIST']._serialized_end=70
  _globals['_VARIANTSTRUCT']._serialized_start=72
  _globals['_VARIANTSTRUCT']._serialized_end=196
  _globals['_VARIANTSTRUCT_FIELDSENTRY']._serialized_start=137
  _globals['_VARIANTSTRUCT_FIELDSENTRY']._serialized_end=196
  _globals['_VARIANT']._serialized_start=199
  _globals['_VARIANT']._serialized_end=452
  _globals['_STREAMREQUEST']._serialized_start=455
  _globals['_STREAMREQUEST']._serialized_end=643
  _globals['_STREAMREQUEST_KWARGSENTRY']._serialized_start=584
  _globals['_STREAMREQUEST_KWARGSENTRY']._serialized_end=643
  _globals['_STREAMRESPONSE']._serialized_start=645
  _globals['_STREAMRESPONSE']._serialized_end=726
  _globals['_TELEMETRYUPDATE']._serialized_start=729
  _globals['_TELEMETRYUPDATE']._serialized_end=894
  _globals['_TELEMETRYUPDATE_MEASUREMENTSENTRY']._serialized_start=829
  _globals['_TELEMETRYUPDATE_MEASUREMENTSENTRY']._serialized_end=894
  _globals['_DUESTREAMING']._serialized_start=926
  _globals['_DUESTREAMING']._serialized_end=1068
# @@protoc_insertion_point(module_scope)
